### PR TITLE
fix: downloads all reports generated on a specific day

### LINKED ISSUE #13: Troubleshoot import of entur sales data
# Background

Data imported by ragnarok, and data in entur-dashboard have discrepancies.

# Proposed solution

Check downloaded files against dash-board data.  Test redownloading files from source

### PR DESCRIPTION
**Pull request by jbtfk**
End of month (and banking holidays) won't generate all the reports until first real working day.
This pull request now downloads all reports generated by (orderBy) CLEOS for any given chunkId

orderDate: date report is generated - can be multiple reports
orderBy: the process/user/entity that placed the order to generate report

Still using the parquet file, since going for BigQuery seems to be a large task to complete

### CODE REVIEW

File: src/Services/EnturSales.php [hunk 1]
```diff
@@ -47,31 +47,57 @@ public function download($chunkId): SinkFile|null
...
+                    return null;
+                }
+
+                if ($archive === null) {
+                    $archive = new ChunkArchive(SinkEnturSales::$id, $chunkId);
+                }
+
+                $archive->addFromString($report->reportName, $reportContent);
+            } else {
+                $continueProcessing = false;
```
Comment (imable) [inline src/Services/EnturSales.php]: This could be a `break;`

**Review by tft-abel — APPROVED** [review]
Small improvement in readability suggested. Looks good otherwise!

File: src/Services/EnturSales.php (hunk 1 above)
Comment (jbtfk) [reply src/Services/EnturSales.php]: It is a break... I dont know what you are talking about ;)

**Review by tfk-kaare — APPROVED** [review]
I have experience with finding the exact same bug and exact same solution when refactoring things! \*ahem\*

I'm very happy with this: Prod vs local dev (this branch):

Image
Image

Commit and rejoice!

**Comment by jbtfk** [comment]
Squashed
